Run 6th test - testGutterGame error-11
Error-11:
AssertionError: test Fail as the result value has to be 16
to compare actual score and assert score ,change method to self.assertEqual instead of assert method
AssertionError: result value is 18 but expected value is 16 . now we have to find error in main code but first complete all test