Run 3rd test - testGutterGame error-7
Error-7:
AssertionError: test Fail as the result value has to be 24
code changed to compare actual result value to expected result value
Actual value is 17 and expected value is 24