Run 4th test - testGutterGame error-8
Error-8:
AssertionError: test Fail as the result value has to be 300
to compare actual score and assert  score ,change method to self.assertEqual instead of assert method
AssertionError: result value is 30 but expected value is 300 . now we have to find error in main code but first complete all test