Run 5th test - testGutterGame error-9
Error-9:
AssertionError: test Fail as the result value has to be 150
to compare actual score and assert score ,change method to self.assertEqual instead of assert method
AssertionError: result value is 20 but expected value is 150 . now we have to find error in main code but first complete all test